# run: conda env create
name: core-dev
channels:
  - conda-forge
dependencies:
  - boto3
  - docutils
  - future
  - h5py
  - matplotlib
  - numpy
  - psutil
  - pyzmq
  - scikit-image
  - scipy
  - scyjava
  - pip:
    - centrosome
